### ISSUE TITLE
Hetzner Cloud CLI: segmentation violation when run 'hcloud server list'

### ISSUE THREAD

**Issue by DayDve** [hetzneronline/community-content#649]
## Problem
If there are a large number of servers (>99) in the active context, then the `hcloud server list` crashed with this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e55a6]

goroutine 1 [running]:
net.networkNumberAndMask(0x0, 0x4, 0xc000036340, 0x48327c, 0xc000088800, 0x0, 0x0)
        net/ip.go:476 +0x26
net.(*IPNet).String(0x0, 0xc0003af8a0, 0xc0004b40d0)
        net/ip.go:526 +0x45
github.com/hetznercloud/cli/cli.describeServerListTableOutput.func2(0x871280, 0xc0001d7760, 0x91fb5b, 0x4)
        github.com/hetznercloud/cli/cli/server_list.go:79 +0x45
github.com/hetznercloud/cli/cli.(*tableOutput).Write(0xc0001cede0, 0xc0001e5c88, 0x6, 0x6, 0x871280, 0xc0001d7760)
        github.com/hetznercloud/cli/cli/output.go:265 +0x2e5
github.com/hetznercloud/cli/cli.runServerList(0xc000107c70, 0xc00013ab00, 0xc5b0f8, 0x0, 0x0, 0x0, 0x0)
        github.com/hetznercloud/cli/cli/server_list.go:64 +0x3ea
github.com/hetznercloud/cli/cli.(*CLI).wrap.func1(0xc00013ab00, 0xc5b0f8, 0x0, 0x0, 0x0, 0x0)
        github.com/hetznercloud/cli/cli/cli.go:118 +0x56
github.com/spf13/cobra.(*Command).execute(0xc00013ab00, 0xc0000a2170, 0x0, 0x0, 0xc00013ab00, 0xc0000a2170)
        github.com/spf13/cobra/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e8580, 0x0, 0x0, 0xc000157ba0)
        github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra/command.go:895
main.main()
        github.com/hetznercloud/cli/cmd/hcloud/main.go:35 +0x65
```

**Comment by wpdevelopment11** [comment]
You're reporting into the wrong repository. This repository stores Hetzner Online Community tutorials.
`hcloud` is developed here: https://github.com/hetznercloud/cli

Take a look at the same issue: https://github.com/hetznercloud/cli/issues/463

**Comment by svenja11** [comment]
Closed because of comment above.
